// ============================================================
// COURSE 2: Literature Search & PRISMA — 70 Questions (10 per category)
// ============================================================
// 7 categories:
//   0 = Systematic vs casual search
//   1 = Databases (PubMed, Embase, Cochrane, etc.)
//   2 = Boolean operators & search syntax (AND, OR, NOT, MeSH, truncation)
//   3 = PRISMA flow diagram
//   4 = Screening process
//   5 = Grey literature & search completeness
//   6 = Search strategy pitfalls & best practices
// ============================================================

export const course2Categories = {
  zh: ["系統性搜尋 vs 隨意搜尋", "文獻資料庫", "布林邏輯與搜尋語法", "PRISMA 流程圖", "篩選流程", "灰色文獻與搜尋完整性", "搜尋策略陷阱與最佳實踐"],
  en: ["Systematic vs Casual Search", "Databases", "Boolean Operators & Search Syntax", "PRISMA Flow Diagram", "Screening Process", "Grey Literature & Search Completeness", "Search Strategy Pitfalls & Best Practices"],
};

export const course2Questions = [

  // Category 0: Systematic vs casual search (10 Qs)
  { id: "c2-001", category: 0, zh: { q: "系統性文獻搜尋和隨意搜尋最大的差別是什麼？", opts: ["系統性搜尋比較快", "系統性搜尋有預先定義的策略、可重複且透明", "隨意搜尋找到的文獻品質較高", "兩者沒有差別"], exp: "系統性搜尋的核心特徵是：預先定義搜尋策略、方法可重複、過程透明可審查。隨意搜尋則依賴個人經驗，容易遺漏重要文獻。" }, en: { q: "What is the key difference between systematic and casual literature searching?", opts: ["Systematic search is faster", "Systematic search uses a predefined, reproducible, and transparent strategy", "Casual search finds higher quality studies", "There is no difference"], exp: "Systematic searching is defined by: predefined strategy, reproducibility, and transparency. Casual searching relies on personal experience and risks missing key studies." }, correct: 1 },
  { id: "c2-002", category: 0, zh: { q: "為什麼系統性回顧需要記錄完整的搜尋策略？", opts: ["為了讓文章看起來更長", "為了可重複性——讓其他研究者能重現你的搜尋", "因為期刊版面需要", "記錄策略不是必要的"], exp: "完整記錄搜尋策略是系統性回顧的核心要求，確保其他研究者能重現搜尋、驗證結果的完整性。" }, en: { q: "Why must a systematic review document the complete search strategy?", opts: ["To make the paper longer", "For reproducibility — so others can replicate your search", "Journals need to fill pages", "Documenting the strategy isn't required"], exp: "Documenting the full search strategy is a core requirement — it ensures others can replicate the search and verify completeness." }, correct: 1 },
  { id: "c2-003", category: 0, zh: { q: "以下哪個是隨意搜尋（非系統性搜尋）的典型問題？", opts: ["搜尋結果太多", "容易遺漏不支持你假設的研究，導致選擇偏差", "搜尋速度太慢", "找到太多高品質的 RCT"], exp: "隨意搜尋傾向找到支持預設立場的文獻，容易遺漏不利證據，造成選擇偏差。" }, en: { q: "What is a typical problem with casual (non-systematic) searching?", opts: ["Too many results", "Tends to miss studies that don't support your hypothesis, causing selection bias", "Too slow", "Finds too many high-quality RCTs"], exp: "Casual searching tends to find studies supporting preconceptions, missing unfavorable evidence — causing selection bias." }, correct: 1 },
  { id: "c2-004", category: 0, zh: { q: "系統性搜尋策略應該在什麼時候制定？", opts: ["寫完結果之後", "在開始搜尋之前，根據 PICO 預先制定", "在篩選完文獻之後", "隨時都可以，沒有順序"], exp: "搜尋策略應在搜尋前根據 PICO 制定，避免事後調整策略以符合預期結果。" }, en: { q: "When should a systematic search strategy be developed?", opts: ["After writing the results", "Before searching, based on the PICO — ideally pre-registered", "After screening studies", "Anytime, order doesn't matter"], exp: "The strategy should be developed before searching, based on PICO, to prevent post-hoc adjustments." }, correct: 1 },
  { id: "c2-005", category: 0, zh: { q: "以下哪個不是系統性搜尋的特徵？", opts: ["涵蓋多個資料庫", "搜尋策略可重複", "只搜尋支持自己假設的文獻", "記錄完整的搜尋過程"], exp: "系統性搜尋的目標是全面、無偏地找到所有相關文獻，而不是只找支持假設的證據。" }, en: { q: "Which is NOT a characteristic of systematic searching?", opts: ["Covers multiple databases", "Search strategy is reproducible", "Only searches for studies supporting your hypothesis", "Documents the full search process"], exp: "Systematic searching aims to find ALL relevant literature comprehensively and without bias." }, correct: 2 },
  { id: "c2-006", category: 0, zh: { q: "建議在制定搜尋策略時諮詢誰？", opts: ["只需要自己一個人做", "醫學圖書館員或資訊專家", "統計學家", "病人"], exp: "醫學圖書館員/資訊專家熟悉各資料庫的特性、搜尋語法和 MeSH 詞彙，是制定高品質搜尋策略的關鍵夥伴。" }, en: { q: "Who should you consult when developing a search strategy?", opts: ["Just do it alone", "A medical librarian or information specialist", "A statistician", "A patient"], exp: "Medical librarians/information specialists know database features, search syntax, and MeSH terms — key partners for high-quality strategies." }, correct: 1 },
  { id: "c2-007", category: 0, zh: { q: "PROSPERO 是什麼？", opts: ["一個文獻資料庫", "系統性回顧的國際前瞻性註冊平台", "一種統計軟體", "PRISMA 的另一個名字"], exp: "PROSPERO 是系統性回顧的前瞻性註冊平台，在搜尋前註冊你的計畫，增加研究透明度。" }, en: { q: "What is PROSPERO?", opts: ["A literature database", "An international prospective register for systematic reviews", "A statistical software", "Another name for PRISMA"], exp: "PROSPERO is a prospective register for systematic reviews. Registering your protocol before searching increases transparency." }, correct: 1 },
  { id: "c2-008", category: 0, zh: { q: "以下哪個情境最需要系統性搜尋而非隨意搜尋？", opts: ["快速回答同事的臨床問題", "撰寫統合分析以制定臨床指引", "瀏覽最新期刊的目錄", "準備期刊讀書會的報告"], exp: "統合分析和臨床指引的結論會直接影響臨床決策，必須用系統性搜尋確保證據的完整性。" }, en: { q: "Which scenario most requires systematic rather than casual searching?", opts: ["Quickly answering a colleague's clinical question", "Conducting a meta-analysis to inform clinical guidelines", "Browsing the latest journal table of contents", "Preparing a journal club presentation"], exp: "Meta-analyses and clinical guidelines directly impact clinical decisions — systematic searching ensures evidence completeness." }, correct: 1 },
  { id: "c2-009", category: 0, zh: { q: "系統性搜尋的「敏感度」和「精確度」之間通常有什麼關係？", opts: ["敏感度越高，精確度也越高", "兩者互相獨立", "提高敏感度通常會降低精確度——找到更多文獻但不相關的也更多", "精確度永遠比敏感度重要"], exp: "敏感度（找到所有相關文獻）和精確度（減少不相關文獻）通常是此消彼長的。系統性回顧優先追求高敏感度。" }, en: { q: "What is the typical relationship between search sensitivity and precision?", opts: ["Higher sensitivity means higher precision", "They are independent", "Increasing sensitivity usually decreases precision — more results but also more noise", "Precision is always more important"], exp: "Sensitivity (finding all relevant studies) and precision (reducing irrelevant ones) are usually trade-offs. Systematic reviews prioritize high sensitivity." }, correct: 2 },
  { id: "c2-010", category: 0, zh: { q: "為什麼系統性回顧不建議只用 Google Scholar 搜尋？", opts: ["Google Scholar 完全沒有用", "Google Scholar 的搜尋演算法不透明、不可完全重複，且缺乏進階搜尋功能", "Google Scholar 只有英文文獻", "Google Scholar 需要付費"], exp: "Google Scholar 的排序演算法不透明，搜尋結果不完全可重複，缺乏 MeSH 等控制詞彙。可作為補充但不能作為唯一來源。" }, en: { q: "Why shouldn't systematic reviews rely solely on Google Scholar?", opts: ["Google Scholar is completely useless", "Its algorithm is opaque, results aren't fully reproducible, and it lacks advanced search features", "It only has English literature", "It requires payment"], exp: "Google Scholar's ranking algorithm is opaque, results aren't fully reproducible, and it lacks controlled vocabularies like MeSH. Useful as supplement, not sole source." }, correct: 1 },

  // Category 1: Databases (10 Qs)
  { id: "c2-011", category: 1, zh: { q: "系統性文獻回顧中，Cochrane 建議至少搜尋幾個資料庫？", opts: ["1 個就夠了", "至少 2 個（如 MEDLINE + Embase）", "至少 5 個", "所有存在的資料庫"], exp: "Cochrane Handbook 建議至少搜尋 MEDLINE 和 Embase，再根據主題加上其他資料庫。" }, en: { q: "How many databases does Cochrane recommend searching at minimum?", opts: ["1 is enough", "At least 2 (e.g., MEDLINE + Embase)", "At least 5", "Every database that exists"], exp: "Cochrane Handbook recommends at least MEDLINE and Embase, plus topic-specific databases as needed." }, correct: 1 },
  { id: "c2-012", category: 1, zh: { q: "PubMed 和 MEDLINE 有什麼關係？", opts: ["完全相同的東西", "PubMed 包含 MEDLINE 加上額外的文獻（如預印本、尚未被索引的文獻）", "MEDLINE 比 PubMed 更大", "兩者完全不同"], exp: "PubMed 是免費搜尋介面，包含 MEDLINE（經 MeSH 索引的文獻）加上尚未索引的新文獻和其他來源。" }, en: { q: "What is the relationship between PubMed and MEDLINE?", opts: ["Exactly the same thing", "PubMed includes MEDLINE plus additional records (ahead-of-print, not-yet-indexed)", "MEDLINE is larger than PubMed", "Completely different with no overlap"], exp: "PubMed is a free search interface containing MEDLINE (MeSH-indexed records) plus additional not-yet-indexed records." }, correct: 1 },
  { id: "c2-013", category: 1, zh: { q: "Embase 相比 PubMed 的主要優勢是什麼？", opts: ["Embase 完全免費", "Embase 對歐洲文獻和藥物/藥理學主題的涵蓋範圍更廣", "Embase 只有英文文獻", "Embase 比 PubMed 更容易使用"], exp: "Embase 涵蓋更多歐洲期刊，且對藥物、藥理學主題的索引特別強。但通常需要付費訂閱。" }, en: { q: "What is Embase's main advantage over PubMed?", opts: ["Embase is completely free", "Broader coverage of European literature and pharmacology/drug topics", "Embase only has English literature", "Embase is easier to use"], exp: "Embase covers more European journals and has particularly strong indexing for drugs and pharmacology. Usually requires a paid subscription." }, correct: 1 },
  { id: "c2-014", category: 1, zh: { q: "Cochrane Library 的主要特色是什麼？", opts: ["包含所有醫學文獻", "專門收錄系統性回顧和臨床試驗的高品質證據資料庫", "只有護理學文獻", "是一個統計軟體"], exp: "Cochrane Library 包含 Cochrane Reviews（系統性回顧）和 CENTRAL（臨床試驗註冊），是實證醫學的核心資源。" }, en: { q: "What is the main feature of the Cochrane Library?", opts: ["Contains all medical literature", "A high-quality evidence database focused on systematic reviews and clinical trials", "Only nursing literature", "It's a statistical software"], exp: "Cochrane Library contains Cochrane Reviews and CENTRAL (clinical trials registry) — a core resource for evidence-based medicine." }, correct: 1 },
  { id: "c2-015", category: 1, zh: { q: "如果你的統合分析主題涉及護理學，除了 PubMed 和 Embase 之外應該加搜哪個資料庫？", opts: ["CINAHL（護理與健康相關文獻索引）", "IEEE Xplore（工程學）", "APA PsycINFO（只搜心理學就好）", "不需要額外搜尋"], exp: "CINAHL 是護理及相關健康專業的核心資料庫，涵蓋許多 PubMed/Embase 未收錄的護理期刊。" }, en: { q: "For a nursing-related meta-analysis, which database should you add?", opts: ["CINAHL (Cumulative Index to Nursing and Allied Health Literature)", "IEEE Xplore (engineering)", "APA PsycINFO (psychology only)", "No additional search needed"], exp: "CINAHL is the core database for nursing and allied health, covering many journals not indexed in PubMed/Embase." }, correct: 0 },
  { id: "c2-016", category: 1, zh: { q: "為什麼同一個搜尋策略在不同資料庫可能需要調整？", opts: ["不需要調整，直接複製貼上就好", "因為不同資料庫使用不同的搜尋語法、控制詞彙和欄位代碼", "因為每個資料庫收錄的文獻完全不重疊", "為了讓搜尋結果數字不同"], exp: "PubMed 用 MeSH，Embase 用 Emtree，搜尋語法也各不相同。必須為每個資料庫調整策略。" }, en: { q: "Why might the same search strategy need adjustment across databases?", opts: ["No adjustment needed — just copy-paste", "Different databases use different search syntax, controlled vocabularies, and field codes", "Databases have zero overlap", "To make result numbers different"], exp: "PubMed uses MeSH, Embase uses Emtree, and search syntax varies. Strategies must be adapted per database." }, correct: 1 },
  { id: "c2-017", category: 1, zh: { q: "CENTRAL 是什麼？", opts: ["一種統計方法", "Cochrane 的臨床試驗註冊資料庫，專門收錄 RCT 和 CCT", "一個基因組學資料庫", "PubMed 的另一個名字"], exp: "CENTRAL 收錄了從多個來源識別出的 RCT 和半隨機對照試驗，是搜尋 RCT 的重要來源。" }, en: { q: "What is CENTRAL?", opts: ["A statistical method", "Cochrane's register of controlled trials, collecting RCTs and CCTs", "A genomics database", "Another name for PubMed"], exp: "CENTRAL collects RCTs and quasi-randomized trials from multiple sources — a key source for finding RCTs." }, correct: 1 },
  { id: "c2-018", category: 1, zh: { q: "Web of Science 在系統性回顧中最常被用來做什麼？", opts: ["取代 PubMed", "追蹤引用文獻——找出引用了某篇關鍵文獻的後續研究", "只用來搜尋社會科學文獻", "計算影響係數"], exp: "WoS 的引用追蹤功能特別有用：找到引用了你已知關鍵文獻的所有後續研究。" }, en: { q: "What is Web of Science most commonly used for in systematic reviews?", opts: ["Replacing PubMed", "Citation tracking — finding studies that cited a key reference", "Only for social science literature", "Calculating impact factors"], exp: "WoS's citation tracking finds all subsequent studies that cited a key paper — an important supplementary search method." }, correct: 1 },
  { id: "c2-019", category: 1, zh: { q: "ClinicalTrials.gov 在系統性回顧中有什麼用途？", opts: ["取代文獻資料庫搜尋", "識別已完成但尚未發表的試驗，幫助偵測發表偏倚", "只有美國的試驗", "用來下載全文"], exp: "ClinicalTrials.gov 記錄了註冊的臨床試驗（包括未發表結果）。搜尋它可以識別發表偏倚。" }, en: { q: "What role does ClinicalTrials.gov play in systematic reviews?", opts: ["Replaces database searching", "Identifies completed but unpublished trials, helping detect publication bias", "Only has US trials", "Used to download full texts"], exp: "ClinicalTrials.gov records registered trials including unpublished results. Searching it helps detect publication bias." }, correct: 1 },
  { id: "c2-020", category: 1, zh: { q: "在選擇資料庫時，「主題特異性」是什麼意思？", opts: ["所有資料庫都涵蓋所有主題", "不同資料庫對特定主題領域的涵蓋深度不同，應根據研究主題選擇", "只需要搜尋一個資料庫", "主題特異性不重要"], exp: "例如心理學主題應加搜 PsycINFO，護理主題加搜 CINAHL。根據 PICO 主題選擇涵蓋最深的資料庫。" }, en: { q: "What does 'subject specificity' mean when choosing databases?", opts: ["All databases cover all topics equally", "Different databases have different depth for specific topics — choose based on your topic", "One database is always enough", "Subject specificity doesn't matter"], exp: "E.g., psychology topics add PsycINFO, nursing adds CINAHL. Choose databases with deepest coverage for your PICO topic." }, correct: 1 },

  // Category 2: Boolean operators & search syntax (10 Qs)
  { id: "c2-021", category: 2, zh: { q: "在搜尋策略中，OR 運算子的作用是什麼？", opts: ["縮小搜尋範圍", "連接不同概念", "連接同義詞，擴大搜尋範圍", "排除不相關的文獻"], exp: "OR 用來連接同一概念的不同表達方式（同義詞），確保不遺漏使用不同術語的文獻。" }, en: { q: "What does the OR operator do in a search strategy?", opts: ["Narrows the search", "Connects different concepts", "Connects synonyms to expand results", "Excludes irrelevant literature"], exp: "OR connects synonyms (different expressions of the same concept), ensuring you don't miss studies using different terms." }, correct: 2 },
  { id: "c2-022", category: 2, zh: { q: "AND 運算子會讓搜尋結果怎樣？", opts: ["增加結果數量", "減少結果數量——只保留同時包含所有概念的文獻", "沒有影響", "隨機選擇文獻"], exp: "AND 要求文獻同時包含所有連接的概念，縮小搜尋範圍。" }, en: { q: "How does the AND operator affect search results?", opts: ["Increases results", "Decreases results — only keeps records containing ALL connected concepts", "No effect", "Randomly selects records"], exp: "AND requires records to contain ALL connected concepts, narrowing results." }, correct: 1 },
  { id: "c2-023", category: 2, zh: { q: "NOT 運算子在搜尋中應該怎麼使用？", opts: ["大量使用以縮小範圍", "謹慎使用——因為可能意外排除相關文獻", "NOT 和 AND 功能相同", "每次搜尋都必須用 NOT"], exp: "NOT 會排除包含指定詞彙的所有文獻，即使該文獻其實是相關的。應謹慎使用。" }, en: { q: "How should the NOT operator be used in searching?", opts: ["Use extensively to narrow results", "Use cautiously — it may accidentally exclude relevant studies", "NOT and AND function the same", "Every search must use NOT"], exp: "NOT excludes ALL records containing the specified term, even if relevant. Use cautiously." }, correct: 1 },
  { id: "c2-024", category: 2, zh: { q: "在搜尋策略中使用 MeSH 詞彙有什麼好處？", opts: ["可以搜到更多不相關的文獻", "MeSH 是標準化的主題詞，能找到所有用了不同術語描述同一概念的文獻", "可以讓搜尋變快", "只有 PubMed 需要用"], exp: "MeSH 是 NLM 的標準化詞彙系統。文獻入庫時被人工標記 MeSH 詞，搜尋時能捕捉各種同義詞。" }, en: { q: "What is the advantage of using MeSH terms?", opts: ["Finds more irrelevant results", "MeSH is standardized vocabulary that captures studies using different terms for the same concept", "Makes searching faster", "Only PubMed uses MeSH"], exp: "MeSH is NLM's standardized vocabulary. Articles are manually tagged with MeSH terms, capturing all synonyms." }, correct: 1 },
  { id: "c2-025", category: 2, zh: { q: "截斷搜尋的用途是什麼？例如 'randomi*'", opts: ["搜尋精確的完整詞彙", "用萬用字元捕捉一個詞根的所有變體（如 randomize, randomized, randomisation）", "排除含有該詞根的文獻", "只在 Embase 有用"], exp: "截斷符號（通常是 *）可以捕捉同一詞根的所有變化形式，避免遺漏不同拼寫或詞形的文獻。" }, en: { q: "What is truncation used for? e.g., 'randomi*'", opts: ["Searching for the exact word", "Using a wildcard to capture all variations of a word stem", "Excluding records with that root", "Only works in Embase"], exp: "Truncation (usually *) captures all variations of a word stem, preventing missed records due to different spellings." }, correct: 1 },
  { id: "c2-026", category: 2, zh: { q: "以下哪個搜尋策略結構最合理？", opts: ["把所有關鍵詞用 AND 連在一起", "(P 的同義詞用 OR 連接) AND (I 的同義詞用 OR 連接) AND (filter)", "只用一個關鍵詞搜尋", "把所有詞用 OR 連在一起"], exp: "標準結構是：每個 PICO 概念內部用 OR 連接同義詞，概念之間用 AND 連接。" }, en: { q: "Which search strategy structure is most appropriate?", opts: ["Connect all keywords with AND", "(P synonyms joined by OR) AND (I synonyms joined by OR) AND (filter)", "Search with just one keyword", "Connect all terms with OR"], exp: "Standard structure: within each PICO concept, join synonyms with OR; between concepts, join with AND." }, correct: 1 },
  { id: "c2-027", category: 2, zh: { q: "「詞組搜尋」用引號括起來的功能是什麼？例如 \"heart failure\"", opts: ["搜尋含有 heart 或 failure 的文獻", "只搜尋完全按這個順序出現的詞組", "排除這個詞組", "和不加引號完全相同"], exp: "引號強制資料庫搜尋精確的詞組，而非分開的個別單詞。" }, en: { q: "What does phrase searching with quotes do? e.g., \"heart failure\"", opts: ["Searches for heart OR failure", "Only searches for the exact phrase in that order", "Excludes the phrase", "Same as without quotes"], exp: "Quotes force the database to search for the exact phrase, not individual words." }, correct: 1 },
  { id: "c2-028", category: 2, zh: { q: "Embase 使用的控制詞彙系統叫什麼？", opts: ["MeSH", "Emtree", "SNOMED", "ICD-10"], exp: "Embase 使用 Emtree 作為其控制詞彙系統，類似於 PubMed 的 MeSH。" }, en: { q: "What is Embase's controlled vocabulary system called?", opts: ["MeSH", "Emtree", "SNOMED", "ICD-10"], exp: "Embase uses Emtree as its controlled vocabulary, similar to PubMed's MeSH." }, correct: 1 },
  { id: "c2-029", category: 2, zh: { q: "MeSH 的「爆炸」(explode) 功能是什麼意思？", opts: ["刪除該 MeSH 詞", "自動包含該 MeSH 詞及其所有下位詞（子類別）", "只搜尋精確的 MeSH 詞", "讓搜尋速度更快"], exp: "Explode 會自動包含該 MeSH 詞的所有下位詞。例如 explode \"Heart Failure\" 會同時搜到其所有子分類。" }, en: { q: "What does 'exploding' a MeSH term mean?", opts: ["Deleting the MeSH term", "Automatically including the term and all its narrower terms", "Only searching the exact MeSH term", "Making the search faster"], exp: "Explode includes the MeSH term plus all narrower terms, e.g., 'Heart Failure' also captures 'Heart Failure, Systolic'." }, correct: 1 },
  { id: "c2-030", category: 2, zh: { q: "為什麼搜尋策略應該同時包含 MeSH 詞和自由文字？", opts: ["只用其中一種就夠了", "MeSH 只能找到已索引的文獻，自由文字可以補充找到新進或尚未索引的文獻", "自由文字比 MeSH 更精確", "只是慣例"], exp: "MeSH 搜尋精確但只涵蓋已索引的文獻。自由文字可以捕捉尚未被 MeSH 索引的新文獻。兩者結合確保最大涵蓋率。" }, en: { q: "Why should a search strategy include both MeSH and free text?", opts: ["One type is enough", "MeSH only finds indexed records; free text catches new or not-yet-indexed records", "Free text is more precise", "Just convention"], exp: "MeSH is precise but only covers indexed records. Free text catches new/not-yet-indexed articles. Combining maximizes coverage." }, correct: 1 },

  // Category 3: PRISMA flow diagram (10 Qs)
  { id: "c2-031", category: 3, zh: { q: "PRISMA 流程圖中，「初篩」通常根據什麼來決定？", opts: ["只看標題", "閱讀全文", "標題和摘要", "作者的知名度"], exp: "初篩階段根據標題和摘要判斷文獻是否可能符合納入標準。全文篩選是下一個階段。" }, en: { q: "In the PRISMA flow diagram, screening is usually based on what?", opts: ["Title only", "Full text reading", "Title and abstract", "Author reputation"], exp: "Screening is based on title and abstract to determine potential eligibility. Full-text review is the next stage." }, correct: 2 },
  { id: "c2-032", category: 3, zh: { q: "PRISMA 2020 流程圖的四個主要階段是什麼？", opts: ["搜尋、閱讀、分析、發表", "辨識、篩選、適格性、納入", "計畫、執行、報告、發表", "搜尋、排除、納入、統計"], exp: "PRISMA 流程圖包含四階段：辨識 → 篩選 → 適格性 → 納入。" }, en: { q: "What are the four main stages of the PRISMA 2020 flow diagram?", opts: ["Search, Read, Analyze, Publish", "Identification, Screening, Eligibility, Included", "Plan, Execute, Report, Publish", "Search, Exclude, Include, Statistics"], exp: "PRISMA flow has four stages: Identification → Screening → Eligibility → Included." }, correct: 1 },
  { id: "c2-033", category: 3, zh: { q: "在 PRISMA 流程圖中，全文篩選階段排除文獻時必須做什麼？", opts: ["只需標記為「排除」", "記錄每篇被排除文獻的具體理由", "請第三方審查者同意", "寫一段文字說明為什麼不好"], exp: "PRISMA 2020 要求在全文篩選階段記錄每篇排除文獻的理由，並在流程圖中報告。" }, en: { q: "When excluding studies at full-text screening in PRISMA, what must you do?", opts: ["Just mark as 'excluded'", "Record the specific reason for excluding each study", "Get a third reviewer to agree", "Write a paragraph about why it's bad"], exp: "PRISMA 2020 requires recording the reason for each full-text exclusion and reporting in the flow diagram." }, correct: 1 },
  { id: "c2-034", category: 3, zh: { q: "PRISMA 2020 相比舊版新增了什麼重要元素？", opts: ["移除了流程圖", "新增了報告來自資料庫以外來源（如灰色文獻、引用追蹤）的文獻流程", "不再需要報告排除理由", "減少了報告項目"], exp: "PRISMA 2020 增加了「其他來源」的獨立路徑，更完整地反映搜尋過程。" }, en: { q: "What important element did PRISMA 2020 add compared to the 2009 version?", opts: ["Removed the flow diagram", "Added a pathway for records from sources beyond databases (grey literature, citation tracking)", "No longer requires exclusion reasons", "Reduced reporting items"], exp: "PRISMA 2020 added a separate pathway for 'other sources', more completely reflecting the search process." }, correct: 1 },
  { id: "c2-035", category: 3, zh: { q: "PRISMA 流程圖中的「去重」應該在哪個階段進行？", opts: ["全文篩選之後", "在辨識階段，合併來自不同資料庫的重複文獻", "在納入階段", "不需要去重"], exp: "去重在辨識階段進行——搜尋多個資料庫會找到重複文獻，去重後才進入篩選階段。" }, en: { q: "At which stage should deduplication occur in PRISMA?", opts: ["After full-text screening", "At identification, merging duplicates from different databases", "At inclusion", "Not needed"], exp: "Deduplication happens at identification — remove duplicates from multiple databases before screening." }, correct: 1 },
  { id: "c2-036", category: 3, zh: { q: "PRISMA 代表什麼？", opts: ["Primary Research In Systematic Meta-Analysis", "Preferred Reporting Items for Systematic Reviews and Meta-Analyses", "Protocol for Reviewing and Including Studies in Meta-Analysis", "Publication Requirements for International Systematic Reviews"], exp: "PRISMA = Preferred Reporting Items for Systematic Reviews and Meta-Analyses。" }, en: { q: "What does PRISMA stand for?", opts: ["Primary Research In Systematic Meta-Analysis", "Preferred Reporting Items for Systematic Reviews and Meta-Analyses", "Protocol for Reviewing and Including Studies", "Publication Requirements for International SRs"], exp: "PRISMA = Preferred Reporting Items for Systematic Reviews and Meta-Analyses." }, correct: 1 },
  { id: "c2-037", category: 3, zh: { q: "PRISMA 流程圖中，「辨識」階段應該報告什麼數字？", opts: ["只報告最終納入的數量", "各資料庫的搜尋結果數量和去重後的數量", "只報告排除的數量", "不需要報告數字"], exp: "辨識階段需報告每個資料庫的檢索結果數、其他來源的數量，以及去重後進入篩選的總數。" }, en: { q: "What numbers should be reported at Identification stage?", opts: ["Only final included count", "Records from each database and count after deduplication", "Only excluded count", "No numbers needed"], exp: "Identification reports records from each database, records from other sources, and total after removing duplicates." }, correct: 1 },
  { id: "c2-038", category: 3, zh: { q: "PRISMA 流程圖可以用什麼工具自動生成？", opts: ["只能手繪", "使用線上工具如 PRISMA Flow Diagram Generator 或 R 套件", "只能用 Word 畫表格", "不需要視覺化"], exp: "有多個免費工具可生成 PRISMA 流程圖，如 PRISMA2020 R 套件和線上生成器。" }, en: { q: "What tools can auto-generate a PRISMA flow diagram?", opts: ["Can only be hand-drawn", "Online tools like PRISMA Flow Diagram Generator or R packages", "Only Word tables", "Don't need visualization"], exp: "Several free tools generate PRISMA diagrams: the PRISMA2020 R package and online generators." }, correct: 1 },
  { id: "c2-039", category: 3, zh: { q: "全文篩選後排除了 50 篇文獻，以下哪種報告方式最符合 PRISMA？", opts: ["只寫「排除 50 篇」", "按排除理由分類報告：15 篇非 RCT、12 篇族群不符、10 篇結果不匹配等", "不需要報告排除的文獻", "只列出排除文獻的作者名單"], exp: "PRISMA 要求按理由分類報告全文排除數量，讓讀者了解排除的具體原因。" }, en: { q: "After excluding 50 studies at full-text, which reporting best follows PRISMA?", opts: ["Just write 'excluded 50'", "Report by reason: 15 not RCT, 12 wrong population, 10 wrong outcome, etc.", "No need to report", "Just list excluded authors"], exp: "PRISMA requires full-text exclusions categorized by reason." }, correct: 1 },
  { id: "c2-040", category: 3, zh: { q: "PRISMA 流程圖在論文的哪個部分呈現？", opts: ["引言", "方法/結果部分，通常作為 Figure 1", "討論", "只放附錄"], exp: "PRISMA 流程圖通常作為論文的第一張圖，放在方法或結果部分。" }, en: { q: "Where in a paper is the PRISMA flow diagram typically presented?", opts: ["Introduction", "Methods/Results section, typically as Figure 1", "Discussion", "Only in appendix"], exp: "The PRISMA flow diagram is typically Figure 1, placed in Methods or Results." }, correct: 1 },

  // Category 4: Screening process (10 Qs)
  { id: "c2-041", category: 4, zh: { q: "為什麼系統性回顧需要至少兩名獨立的審查者？", opts: ["因為工作量太大", "為了減少偏差、提高篩選的可靠性", "因為期刊規定", "為了更快完成"], exp: "獨立雙人篩選可以減少個人主觀偏差，提高結果的可靠性和可重複性。" }, en: { q: "Why does a systematic review need at least two independent reviewers?", opts: ["Workload is too much for one", "To reduce bias and improve reliability", "Journals require it", "To finish faster"], exp: "Independent dual screening reduces subjective bias and improves reliability — a core methodological requirement." }, correct: 1 },
  { id: "c2-042", category: 4, zh: { q: "當兩名審查者在篩選結果上有分歧時，通常怎麼解決？", opts: ["隨機選一個人的結果", "由第三名審查者仲裁，或討論達成共識", "直接排除有爭議的文獻", "不需要解決"], exp: "分歧通常先由兩人討論解決。如果無法達成共識，由第三名審查者做最終決定。" }, en: { q: "How are reviewer disagreements typically resolved?", opts: ["Randomly pick one decision", "Third reviewer arbitrates, or discussion until consensus", "Exclude all disputed studies", "No resolution needed"], exp: "Disagreements are first resolved by discussion. If no consensus, a third reviewer decides." }, correct: 1 },
  { id: "c2-043", category: 4, zh: { q: "在標題/摘要篩選時，如果不確定某篇文獻是否相關，應該怎麼做？", opts: ["直接排除以節省時間", "納入到全文篩選——寧可多看也不要遺漏", "只看標題決定", "擲硬幣"], exp: "不確定的文獻應保留到全文篩選階段。初篩的原則是「寧可納入也不要遺漏」。" }, en: { q: "During title/abstract screening, if unsure about relevance, what should you do?", opts: ["Exclude to save time", "Include for full-text review — when in doubt, keep it in", "Decide on title only", "Flip a coin"], exp: "Uncertain records should be kept for full-text review. The principle is 'when in doubt, include'." }, correct: 1 },
  { id: "c2-044", category: 4, zh: { q: "篩選前應該先做什麼來確保審查者之間的一致性？", opts: ["不需要任何準備", "進行校準練習——先用一小批文獻測試篩選標準的理解一致性", "讓最資深的人單獨決定", "直接開始篩選"], exp: "校準練習讓所有審查者用同一批文獻測試納入/排除標準的應用，確認理解一致後再正式開始。" }, en: { q: "What should be done before screening to ensure reviewer consistency?", opts: ["No preparation needed", "Pilot testing — calibrate criteria understanding on a small batch", "Senior person decides alone", "Start directly, adjust later"], exp: "Pilot testing has all reviewers screen the same small batch to calibrate. This greatly reduces later disagreements." }, correct: 1 },
  { id: "c2-045", category: 4, zh: { q: "以下哪個工具常用於管理文獻篩選流程？", opts: ["Microsoft Word", "Covidence、Rayyan 或 ASReview 等篩選平台", "Google 搜尋", "Instagram"], exp: "Covidence、Rayyan 和 ASReview 專門設計用於系統性回顧的文獻篩選。" }, en: { q: "Which tools are commonly used to manage screening?", opts: ["Microsoft Word", "Platforms like Covidence, Rayyan, or ASReview", "Google Search", "Instagram"], exp: "Covidence, Rayyan, and ASReview are purpose-built for systematic review screening." }, correct: 1 },
  { id: "c2-046", category: 4, zh: { q: "Cohen's kappa 在篩選過程中用來衡量什麼？", opts: ["文獻的品質", "兩名審查者之間的篩選一致性", "搜尋的敏感度", "效果量"], exp: "Cohen's kappa 量化兩名審查者之間超越隨機一致的同意程度。κ ≥ 0.6 通常被認為可接受。" }, en: { q: "What does Cohen's kappa measure in screening?", opts: ["Study quality", "Inter-rater agreement between two reviewers", "Search sensitivity", "Effect size"], exp: "Cohen's kappa quantifies agreement beyond chance between two reviewers. κ ≥ 0.6 is generally acceptable." }, correct: 1 },
  { id: "c2-047", category: 4, zh: { q: "全文篩選時發現族群不符合 PICO，你應該怎麼做？", opts: ["還是納入", "排除，並記錄理由為「族群不符」", "修改 PICO", "忽略標準"], exp: "應嚴格按照預定的標準執行。族群不符就排除並記錄理由。" }, en: { q: "During full-text screening, population doesn't match PICO. What do you do?", opts: ["Include anyway", "Exclude and record reason as 'population mismatch'", "Change PICO", "Ignore the criterion"], exp: "Apply criteria strictly. Exclude for population mismatch and record the reason." }, correct: 1 },
  { id: "c2-048", category: 4, zh: { q: "以下哪個不是全文排除的合理理由？", opts: ["研究設計不符", "結果指標不匹配", "作者的名字你不認識", "介入措施不符合 PICO"], exp: "排除理由應基於預定標準，而非主觀因素如作者知名度。" }, en: { q: "Which is NOT a valid reason for full-text exclusion?", opts: ["Wrong study design", "Outcome doesn't match", "You don't recognize the author", "Intervention doesn't match PICO"], exp: "Exclusion reasons must be based on pre-defined criteria, not subjective factors like author recognition." }, correct: 2 },
  { id: "c2-049", category: 4, zh: { q: "AI 輔助篩選工具（如 ASReview）的主要優勢是什麼？", opts: ["可以完全取代人工篩選", "利用機器學習優先排序可能相關的文獻，加速篩選", "結果一定比人類準確", "不需要設定標準"], exp: "AI 工具通過主動學習優先呈現最可能相關的文獻。但仍需要人工審查和最終決定。" }, en: { q: "What is the main advantage of AI-assisted screening tools?", opts: ["Completely replaces manual screening", "Uses ML to prioritize likely relevant records, speeding up screening", "Always more accurate than humans", "No criteria needed"], exp: "AI tools use active learning to surface likely relevant records first. But human review and final decisions are still required." }, correct: 1 },
  { id: "c2-050", category: 4, zh: { q: "搜尋到 > 5000 篇文獻時，以下哪個做法最合適？", opts: ["隨機抽取 200 篇", "使用文獻管理軟體去重後系統性篩選", "放棄題目", "只看前 100 篇"], exp: "大量文獻是正常的。使用文獻管理軟體去重，再系統性篩選。" }, en: { q: "When search results exceed 5000 records, what is most appropriate?", opts: ["Randomly sample 200", "Use reference management software to deduplicate, then screen systematically", "Abandon the topic", "Only look at first 100"], exp: "Large volumes are normal. Use reference management software to deduplicate, then screen systematically." }, correct: 1 },

  // Category 5: Grey literature & search completeness (10 Qs)
  { id: "c2-051", category: 5, zh: { q: "什麼是「灰色文獻」？", opts: ["品質很差的文獻", "很舊的文獻", "未經正式期刊發表的研究資料", "只有英文的文獻"], exp: "灰色文獻包括會議摘要、學位論文、技術報告等未經同行評審的正式發表。" }, en: { q: "What is 'grey literature'?", opts: ["Poor quality literature", "Very old literature", "Research not formally published in peer-reviewed journals", "English-only literature"], exp: "Grey literature includes conference abstracts, dissertations, and technical reports not formally peer-reviewed." }, correct: 2 },
  { id: "c2-052", category: 5, zh: { q: "為什麼搜尋灰色文獻可以減少發表偏倚？", opts: ["灰色文獻品質比較高", "因為陰性結果的研究比較不容易被期刊發表，灰色文獻可以補充這些遺漏", "灰色文獻比較新", "不會減少偏倚"], exp: "發表偏倚指陽性結果比陰性結果更容易被發表。灰色文獻中包含許多未發表的陰性結果研究。" }, en: { q: "Why does searching grey literature reduce publication bias?", opts: ["Grey literature is higher quality", "Studies with negative results are less likely published — grey literature captures these", "It's more recent", "It doesn't reduce bias"], exp: "Publication bias means positive results get published more often. Grey literature contains many unpublished negative studies." }, correct: 1 },
  { id: "c2-053", category: 5, zh: { q: "以下哪個是灰色文獻的來源？", opts: ["PubMed 的正式索引文獻", "會議摘要、學位論文、政府報告、臨床試驗註冊結果", "Impact Factor 最高的期刊", "只有 RCT"], exp: "灰色文獻來源包括：會議論文集、博碩士論文、政府/機構報告、ClinicalTrials.gov 結果等。" }, en: { q: "Which is a source of grey literature?", opts: ["Formally indexed PubMed records", "Conference abstracts, dissertations, government reports, trial registry results", "Highest impact factor journals", "Only RCTs"], exp: "Grey literature sources include conference proceedings, theses, government reports, ClinicalTrials.gov results." }, correct: 1 },
  { id: "c2-054", category: 5, zh: { q: "「引用追蹤」在補充搜尋中有什麼作用？", opts: ["計算影響係數", "從已知關鍵文獻出發，找出引用它的後續研究和它引用的參考文獻", "只是為了增加引用次數", "替代資料庫搜尋"], exp: "前向追蹤（誰引用了這篇）和後向追蹤（這篇引用了誰）可以找到資料庫搜尋遺漏的文獻。" }, en: { q: "What role does citation tracking play in supplementary searching?", opts: ["Calculating impact factor", "Finding studies that cited a key paper (forward) and its references (backward)", "Just to increase citations", "Replaces database searching"], exp: "Forward tracking (who cited this?) and backward tracking (what did this cite?) find studies missed by database searches." }, correct: 1 },
  { id: "c2-055", category: 5, zh: { q: "「手動搜尋」指的是什麼？", opts: ["用手寫關鍵詞", "逐期逐頁翻閱特定期刊的目錄，尋找相關文獻", "只用一隻手打字", "不使用電腦的搜尋"], exp: "手動搜尋是逐期翻閱特定核心期刊的目錄，找出電子資料庫可能遺漏的文獻。" }, en: { q: "What does 'handsearching' mean?", opts: ["Writing keywords by hand", "Manually browsing journals issue-by-issue to find relevant articles", "Searching with one hand", "Searching without a computer"], exp: "Handsearching is manually browsing key journals issue-by-issue to find articles missed by electronic databases." }, correct: 1 },
  { id: "c2-056", category: 5, zh: { q: "設定語言限制（如只搜英文）會有什麼風險？", opts: ["沒有風險", "可能遺漏在其他語言發表的相關研究，引入語言偏差", "英文文獻品質一定最好", "其他語言的研究都是重複的"], exp: "語言限制可能排除在非英語期刊發表的重要研究。Cochrane 建議盡量不設語言限制。" }, en: { q: "What risk does a language restriction (English only) pose?", opts: ["No risk", "May miss relevant studies in other languages, introducing language bias", "English studies are always best", "Non-English studies are duplicates"], exp: "Language restrictions may exclude important non-English studies. Cochrane recommends avoiding language limits." }, correct: 1 },
  { id: "c2-057", category: 5, zh: { q: "以下哪個方法可以確認搜尋策略的完整性？", opts: ["不需要確認", "用已知要被納入的關鍵研究測試搜尋策略是否能找到它們", "只搜尋一個資料庫", "只問一位專家"], exp: "在正式搜尋前，用「黃金標準」文獻測試策略。如果策略找不到它們，需要修改。" }, en: { q: "How can you verify search strategy completeness?", opts: ["No verification needed", "Test with known key studies to check if the strategy retrieves them", "Search only one database", "Ask just one expert"], exp: "Test with a 'gold standard' set of known studies. If the strategy misses them, it needs revision." }, correct: 1 },
  { id: "c2-058", category: 5, zh: { q: "搜尋更新通常在什麼時候進行？", opts: ["不需要更新", "在分析和寫作期間——因為新研究可能在搜尋之後發表", "只在投稿被拒之後", "在搜尋的同一天"], exp: "從初始搜尋到論文發表可能間隔數月。更新搜尋確保納入新發表的相關研究。" }, en: { q: "When should a search update be performed?", opts: ["No update needed", "During analysis/writing — new studies may have been published since initial search", "Only after rejection", "Same day as initial search"], exp: "Months may pass between initial search and publication. Updates ensure newly published studies are captured." }, correct: 1 },
  { id: "c2-059", category: 5, zh: { q: "「聯繫作者」在搜尋中有什麼用途？", opts: ["只是禮貌性問候", "取得未發表的資料、釐清方法學細節、確認是否有遺漏的研究", "請作者幫我們寫論文", "不需要聯繫"], exp: "聯繫通訊作者可以取得未發表的資料、補充資訊，或確認是否有我們遺漏的研究。" }, en: { q: "What is the purpose of contacting authors during searching?", opts: ["Just courtesy", "Obtaining unpublished data, clarifying methods, confirming if we missed studies", "Asking them to write our paper", "Not needed"], exp: "Contacting authors can yield unpublished data, supplementary info, or identify missed studies." }, correct: 1 },
  { id: "c2-060", category: 5, zh: { q: "以下哪個做法最能確保搜尋的「可重複性」？", opts: ["口頭描述搜尋過程", "在附錄中提供每個資料庫的完整搜尋語句、日期和結果數量", "只記錄最終納入的文獻", "不需要記錄"], exp: "完整記錄每個資料庫的搜尋語句、日期和結果數量，讓任何人都能精確重現搜尋。" }, en: { q: "Which practice best ensures search reproducibility?", opts: ["Verbally describe the process", "Provide complete queries, dates, and result counts for each database in an appendix", "Only record included studies", "No documentation needed"], exp: "Documenting full queries, dates, and counts for each database allows exact replication — a fundamental requirement." }, correct: 1 },

  // Category 6: Search strategy pitfalls & best practices (10 Qs)
  { id: "c2-061", category: 6, zh: { q: "以下哪個是搜尋策略的常見錯誤？", opts: ["使用 MeSH 和自由文字結合", "只搜尋一個資料庫就認為搜尋完成", "諮詢醫學圖書館員", "做校準測試"], exp: "只搜尋一個資料庫會遺漏大量文獻。至少應搜尋 2-3 個互補的資料庫。" }, en: { q: "Which is a common search strategy mistake?", opts: ["Combining MeSH and free text", "Searching only one database and considering it complete", "Consulting a librarian", "Pilot testing"], exp: "Searching just one database misses substantial literature. Search at least 2-3 complementary databases." }, correct: 1 },
  { id: "c2-062", category: 6, zh: { q: "以下哪個搜尋問題會導致遺漏太多文獻？", opts: ["使用太多 OR 連接同義詞", "使用太多 AND 連接不同概念", "搜尋多個資料庫", "使用截斷搜尋"], exp: "AND 是縮小範圍的運算子。把太多概念用 AND 連接會讓結果太少甚至為零。" }, en: { q: "Which search problem causes missing too many studies?", opts: ["Too many OR for synonyms", "Too many AND joining concepts — each AND narrows dramatically", "Multiple databases", "Using truncation"], exp: "AND narrows results. Too many concepts joined with AND may yield too few or zero results." }, correct: 1 },
  { id: "c2-063", category: 6, zh: { q: "同行評審搜尋策略的 PRESS 清單是什麼？", opts: ["一種統計方法", "一個檢核表，用於同行評審搜尋策略的品質", "一個文獻資料庫", "PRISMA 的另一個名字"], exp: "PRESS 讓第二個人系統性地檢查搜尋策略的品質，包括詞彙選擇、邏輯、語法等。" }, en: { q: "What is the PRESS checklist?", opts: ["A statistical method", "A checklist for peer-reviewing search strategy quality", "A database", "Another name for PRISMA"], exp: "PRESS (Peer Review of Electronic Search Strategies) is a checklist for systematically reviewing search quality." }, correct: 1 },
  { id: "c2-064", category: 6, zh: { q: "使用太寬泛的截斷可能造成什麼問題？例如 'car*'", opts: ["不會有問題", "會捕捉太多不相關的變體（carbon, cardiac, carpet），產生大量噪音", "會讓搜尋速度變慢", "截斷只適用於 Embase"], exp: "太短的詞根會匹配大量不相關的詞。應選擇夠長的詞根或改用精確詞彙。" }, en: { q: "What problem can overly broad truncation cause? e.g., 'car*'", opts: ["No problem", "Captures too many irrelevant variants (carbon, cardiac, carpet)", "Slows the search", "Only works in Embase"], exp: "Too-short stems match many irrelevant terms. Use longer stems or exact terms." }, correct: 1 },
  { id: "c2-065", category: 6, zh: { q: "以下哪個做法可以幫助確保你沒有遺漏重要的同義詞？", opts: ["只用自己想到的詞", "查閱相關系統性回顧的搜尋策略、MeSH 詞樹和 Emtree 來識別同義詞", "只用 MeSH", "不需要擔心同義詞"], exp: "參考已發表的系統性回顧搜尋策略、瀏覽 MeSH 詞樹和 Emtree 階層，系統性地識別同義詞。" }, en: { q: "How can you ensure you haven't missed important synonyms?", opts: ["Just use terms you think of", "Check related SR search strategies, MeSH tree, and Emtree to identify synonyms", "Only use MeSH", "Don't worry about synonyms"], exp: "Review published SR strategies, MeSH tree, and Emtree hierarchies to systematically identify synonyms." }, correct: 1 },
  { id: "c2-066", category: 6, zh: { q: "在搜尋策略中加入研究設計篩選器（如 RCT filter）的時機是什麼？", opts: ["永遠不要用", "在確認搜尋結果數量可管理後，如果需要才使用", "一開始就一定要加", "只有結果為零時才用"], exp: "篩選器可以縮小結果但可能遺漏文獻。建議先不加篩選器評估結果量，必要時才加上。" }, en: { q: "When should study design filters (e.g., RCT filter) be added?", opts: ["Never", "After confirming volume is manageable — only add if further narrowing needed", "Must include from the start", "Only when results are zero"], exp: "Filters narrow results but may miss records. Assess volume without filters first; add only if needed." }, correct: 1 },
  { id: "c2-067", category: 6, zh: { q: "以下哪個是「搜尋策略和 PICO 脫節」的例子？", opts: ["策略包含 PICO 所有概念的同義詞", "PICO 定義了特定藥物，但搜尋策略中沒有該藥物名稱", "使用了 MeSH 和自由文字", "諮詢了圖書館員"], exp: "搜尋策略必須忠實反映 PICO。如果 PICO 中的藥物在策略中缺失，會遺漏所有相關文獻。" }, en: { q: "Which is an example of 'search strategy disconnected from PICO'?", opts: ["Strategy includes all PICO synonyms", "PICO defines a specific drug but strategy doesn't include it", "Uses MeSH and free text", "Consulted a librarian"], exp: "The search strategy must reflect each PICO element. Missing a PICO drug means missing all relevant studies." }, correct: 1 },
  { id: "c2-068", category: 6, zh: { q: "為什麼不建議在搜尋策略中加入 Outcome 的搜尋詞？", opts: ["Outcome 不重要", "因為不同研究描述結果的術語差異很大，加入 O 可能遺漏重要研究", "Outcome 太容易搜尋", "可以加入，沒問題"], exp: "Outcome 描述方式極其多樣。大多數專家建議只用 P 和 I 搜尋，在篩選階段再根據 O 判斷。" }, en: { q: "Why is it discouraged to include Outcome terms in the search?", opts: ["Outcome doesn't matter", "Studies describe outcomes with highly variable terminology — including O may miss studies", "Outcome is too easy to search", "Including it is fine"], exp: "Outcome descriptions are extremely variable. Most experts recommend searching with P and I only, filtering by O during screening." }, correct: 1 },
  { id: "c2-069", category: 6, zh: { q: "搜尋策略附錄應該包含哪些資訊？", opts: ["只需要寫「搜尋了 PubMed」", "每個資料庫的完整搜尋語句、搜尋日期、結果數量", "只需要最終納入的文獻", "不需要報告"], exp: "完整的搜尋報告應包括每個資料庫的名稱、完整語句、搜尋日期和結果數。這是 PRISMA-S 的要求。" }, en: { q: "What should the search strategy appendix contain?", opts: ["Just 'searched PubMed'", "Full queries for each database, search dates, and result counts", "Only included studies", "No reporting needed"], exp: "Complete reporting includes database names, full queries, dates, and per-line result counts. Required by PRISMA-S." }, correct: 1 },
  { id: "c2-070", category: 6, zh: { q: "PRISMA-S 是什麼？和 PRISMA 有什麼關係？", opts: ["和 PRISMA 完全無關", "PRISMA-S 是 PRISMA 的搜尋策略報告擴展，專門針對搜尋方法的報告標準", "是統計方法的指引", "只適用於 Cochrane 回顧"], exp: "PRISMA-S (PRISMA for Searching) 是 2021 年發表的擴展指引，提供了 16 項搜尋報告的具體要求。" }, en: { q: "What is PRISMA-S and how does it relate to PRISMA?", opts: ["Completely unrelated", "An extension of PRISMA specifically for reporting search methods", "A statistical methods guideline", "Only for Cochrane reviews"], exp: "PRISMA-S (PRISMA for Searching) is a 2021 extension with 16 specific search reporting requirements." }, correct: 1 },
];

